name: Deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Deploy to production
        run: |
          cd /var/www/website-links/
          git stash
          git pull origin master
