name: Deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Deploy to production
        run: |
          cd /home/natchi/website-links/
          git stash
          git pull origin master
          rm -r /var/www/website-links/
          cp -a /home/natchi/website-links/src/ /var/www/website-links/